### PR TITLE
added retry strategy on SUPPORTED_REDIS_OPTIONS

### PR DESCRIPTION
**Pull request by jbpin**
This is to support retry_strategy using sol-redis-pool

### CODE REVIEW

**Comment by afrasso** [comment]
I also need this, thanks!

**Comment by mrister** [comment]
@joshuah Any chance on merging this soon?

**Comment by joshuah** [comment]
I am working on a new branch to add this. There are several deprecated options that are related.

**Comment by joshuah** [comment]
Added to version 0.3.0.

**Pull request closed without merging**
