### PR TITLE
Select redis DB on on redis client creation if user specified one

### PR DESCRIPTION
**Pull request by PuKoren**

### CODE REVIEW

**Comment by joshuah** [comment]
I will try to look at merging this request and updating the documentation this week.

**Comment by bf** [comment]
What is the state on this? No action since two months..

**Comment by joshuah** [comment]
The problem is that you end up releasing an object back into the pool that could be attached to a different db. I have not had time to work on a sane way to detect when this happens.

You already can use the select command after you get the redis object.

**Comment by joshuah** [comment]
Please see branch dbselect.

https://github.com/joshuah/sol-redis-pool/tree/dbselect

**Comment by joshuah** [comment]
New version published to npm.

**Pull request closed without merging**
